include(cmake/defaults/CompilerWarnings.cmake)
include(cmake/defaults/Errors.cmake)
include(cmake/defaults/PVSStudio.cmake)
include(cmake/defaults/Sanitizers.cmake)
include(cmake/defaults/Windows.cmake)
